language: python

python:
  - "2.7"
  - "3.5"

install:
  "pip install -r requirements.txt"

script:
  - pytest test/

matrix:
  include:
    - env: LINT_CHECK
      python: "2.7"
      install: pip install flake8
      script: flake8
