language: python

branches:
  only:
    - master
    - travis_fix

python:
  - "2.7"
  - "3.6"
env:
  - PYTORCH_VERSION=4
  - PYTORCH_VERSION=master

install:
  - if [[ $PYTORCH_VERSION == "master" ]]; then
      pip install torch_nightly -v -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
    elif [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl;
    else
      pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl;
    fi
  - python setup.py build develop

script:
  - python -c "import torch; print('PyTorch Version:', torch.__version__)"
  - python -m unittest discover

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
